"use client";
import { useEffect, useState } from "react";
import type { AnalysisViewModel } from "../analysis-types";
import { PerformanceModule } from "./PerformanceModule";
import { TeamMetricsModule } from "./TeamMetricsModule";
type Saved = AnalysisViewModel & { id: string; createdAt: string; createdBy: string; uploads: Array<{ kind: string; filename: string; createdAt: string }> };
export function AnalysisDetailView({ id, onBack }: { id: string; onBack(): void }) {
  const [analysis, setAnalysis] = useState<Saved | null>(null), [error, setError] = useState<string | null>(null);
  useEffect(() => { fetch(`/api/analyses/${encodeURIComponent(id)}`).then(async (response) => { const body = await response.json() as { ok: boolean; analysis?: Saved; issues?: Array<{ message: string }> }; if (response.ok && body.ok && body.analysis) setAnalysis(body.analysis); else setError(body.issues?.[0]?.message ?? "This analysis is unavailable."); }).catch(() => setError("This analysis is unavailable.")); }, [id]);
  if (error) return <div className="welcome-state"><h1>Analysis unavailable</h1><p>{error}</p><button className="primary-button" onClick={onBack}>Back to History</button></div>;
  if (!analysis) return <div className="welcome-state"><h1>Loading saved analysis…</h1></div>;
  const events = analysis.volunteers.flatMap((volunteer) => volunteer.events.map((event) => ({ volunteer, event })));
  return <div className="detail-view"><button className="back-link" onClick={onBack}>← Back to History</button><p className="eyebrow">IMMUTABLE ANALYSIS</p><h1>{analysis.configuration.schoolYearLabel} analysis</h1><p className="heading-note">Created {new Date(analysis.createdAt).toLocaleString()} by {analysis.createdBy}. This record does not change when future rules change.</p><div className="stat-grid analysis-stats"><div className="stat-card"><div className="stat-label">Volunteers</div><div className="stat-value">{analysis.summary.volunteers}</div></div><div className="stat-card accent-coral"><div className="stat-label">Needs review</div><div className="stat-value">{analysis.summary.flaggedOptionalEvents}</div></div><div className="stat-card"><div className="stat-label">Warnings</div><div className="stat-value">{analysis.summary.warnings}</div></div></div><div className="table-card"><div className="table-meta"><span>{events.length} saved event registrations</span><span className="meta-divider" /><span>{analysis.configuration.capHours}-hour cap</span></div><div className="saved-event-list">{events.map(({ volunteer, event }) => <div className="saved-event" key={`${volunteer.volunteerKey}-${event.eventName}-${event.eventDate}`}><div><strong>{volunteer.name}</strong><span>{event.eventName} · {new Date(event.eventDate).toLocaleDateString()}</span></div><span className={`status-pill ${event.classification === "flagged" ? "review" : event.classification === "allowed" ? "allowed" : "exempt"}`}><i />{event.classification === "flagged" ? "Review / remove" : event.classification === "allowed" ? "Allowed" : "Mandatory · exempt"}</span></div>)}</div></div>{analysis.performance && <PerformanceModule performance={analysis.performance} />}{analysis.teamMetrics && <TeamMetricsModule teamMetrics={analysis.teamMetrics} />}</div>;
}
