"use client";
import { useState, type FormEvent } from "react";
import type { AnalysisIssue, AnalysisViewModel } from "../analysis-types";
type Props = { open: boolean; onClose(): void; onSuccess(result: AnalysisViewModel): void };
export function AnalysisUploadModal({ open, onClose, onSuccess }: Props) {
  const [teamReport, setTeamReport] = useState<File | null>(null), [upcomingReport, setUpcomingReport] = useState<File | null>(null), [rosterReport, setRosterReport] = useState<File | null>(null);
  const [schoolYearStart, setSchoolYearStart] = useState("2026-08-01"), [schoolYearEnd, setSchoolYearEnd] = useState("2027-07-31"), [capHours, setCapHours] = useState(25);
  const [issues, setIssues] = useState<AnalysisIssue[]>([]), [submitting, setSubmitting] = useState(false), [saveToHistory, setSaveToHistory] = useState(false);
  if (!open) return null;
  const valid = teamReport && upcomingReport && schoolYearStart && schoolYearEnd && schoolYearEnd >= schoolYearStart && capHours > 0;
  async function submit(event: FormEvent) { event.preventDefault(); if (!valid || submitting) return; setSubmitting(true); setIssues([]); const form = new FormData(); form.set("teamReport", teamReport); form.set("upcomingReport", upcomingReport); if (rosterReport) form.set("rosterReport", rosterReport); form.set("schoolYearStart", schoolYearStart); form.set("schoolYearEnd", schoolYearEnd); form.set("capHours", String(capHours)); if (saveToHistory) form.set("save", "true"); try { const response = await fetch("/api/analyses", { method: "POST", body: form }); const body = await response.json() as { ok: boolean; analysis?: AnalysisViewModel; issues?: AnalysisIssue[] }; if (!response.ok || !body.ok || !body.analysis) setIssues(body.issues ?? [{ code: "ANALYSIS_FAILED", message: "We could not analyze those reports. Please try again." }]); else { onSuccess(body.analysis); onClose(); } } catch { setIssues([{ code: "NETWORK_ERROR", message: "The analysis request could not be completed. Please try again." }]); } finally { setSubmitting(false); } }
  return <div className="modal-backdrop" onClick={submitting ? undefined : onClose}><form className="upload-modal" onSubmit={submit} onClick={(event) => event.stopPropagation()}><button type="button" className="modal-close" onClick={onClose} disabled={submitting} aria-label="Close">×</button><div className="modal-kicker">NEW ANALYSIS</div><h2>Bring in the latest reports.</h2><p>Upload both Helper Helper exports. Results are processed privately; choose Save to History below to keep this snapshot.</p>
    <label className="upload-field"><span>01</span><div><strong>Team Report</strong><small>{teamReport?.name ?? "Completed and validated hours · .xlsx"}</small></div><input type="file" accept=".xlsx" disabled={submitting} onChange={(event) => setTeamReport(event.target.files?.[0] ?? null)} /></label>
    <label className="upload-field"><span>02</span><div><strong>Upcoming Opportunities</strong><small>{upcomingReport?.name ?? "Future registrations and durations · .xlsx"}</small></div><input type="file" accept=".xlsx" disabled={submitting} onChange={(event) => setUpcomingReport(event.target.files?.[0] ?? null)} /></label>
    <label className="upload-field"><span>03</span><div><strong>Full Roster <em>optional</em></strong><small>{rosterReport?.name ?? "Include students with no activity · .xlsx"}</small></div><input type="file" accept=".xlsx" disabled={submitting} onChange={(event) => setRosterReport(event.target.files?.[0] ?? null)} /></label>
    <div className="analysis-config"><label>School-year start<input type="date" value={schoolYearStart} disabled={submitting} onChange={(event) => setSchoolYearStart(event.target.value)} /></label><label>School-year end<input type="date" value={schoolYearEnd} disabled={submitting} onChange={(event) => setSchoolYearEnd(event.target.value)} /></label><label>Hour cap<input type="number" min="0.25" step="0.25" value={capHours} disabled={submitting} onChange={(event) => setCapHours(Number(event.target.value))} /></label></div>
    {issues.length > 0 && <div className="issue-list" role="alert"><strong>Please correct these report issues:</strong><ul>{issues.map((item, index) => <li key={`${item.code}-${index}`}>{item.message}{item.sheet ? ` (${item.sheet}${item.row ? `, row ${item.row}` : ""})` : ""}</li>)}</ul></div>}
    <label className="save-choice"><input type="checkbox" checked={saveToHistory} disabled={submitting} onChange={(event) => setSaveToHistory(event.target.checked)} /> Save this analysis to History</label><div className="submit-status" aria-live="polite">{submitting ? "Analyzing reports…" : "No emails are sent and no registrations are changed."}</div><button className="primary-button full-width" type="submit" disabled={!valid || submitting}>{submitting ? "Analyzing reports…" : saveToHistory ? "Analyze & save →" : "Analyze reports →"}</button>
  </form></div>;
}
