"use client";
import { useMemo, useState } from "react";
import type { AnalysisEvent, AnalysisViewModel, AnalysisVolunteer } from "../analysis-types";
import { PerformanceModule } from "./PerformanceModule";
import { TeamMetricsModule } from "./TeamMetricsModule";
type Props = { analysis: AnalysisViewModel | null; onNewAnalysis(): void }; type Row = { volunteer: AnalysisVolunteer; event: AnalysisEvent };
const label = { allowed: "Allowed", flagged: "Review / remove", mandatory_exempt: "Mandatory · exempt" } as const;
const initials = (name: string) => name.split(/\s+/).map((part) => part[0]).join("").slice(0, 2).toUpperCase();
const formatHours = (hours: number) => new Intl.NumberFormat("en-US", { maximumFractionDigits: 2 }).format(hours);
export function AnalysisDashboard({ analysis, onNewAnalysis }: Props) {
  const [filter, setFilter] = useState("all"), [copied, setCopied] = useState<string | null>(null);
  const rows = useMemo<Row[]>(() => analysis?.volunteers.flatMap((volunteer) => volunteer.events.map((event) => ({ volunteer, event }))) ?? [], [analysis]); const visible = filter === "all" ? rows : rows.filter(({ event }) => event.classification === filter);
  async function copy(row: Row) { if (!row.event.draft) return; await navigator.clipboard.writeText(row.event.draft.copyText); setCopied(`${row.volunteer.volunteerKey}-${row.event.eventName}`); window.setTimeout(() => setCopied(null), 1800); }
  if (!analysis) return <div className="welcome-state"><div className="welcome-mark">＋</div><p className="eyebrow">NEW ANALYSIS</p><h1>Keep opportunities <em>fair.</em></h1><p>Upload the latest Helper Helper reports to replace demonstration data with a real, private calculation.</p><button className="primary-button" onClick={onNewAnalysis}>Choose reports</button><div className="privacy-strip">Processed in memory · Nothing saved to History · No emails sent automatically</div></div>;
  const saved = Boolean(analysis.id);
  return <><div className="analysis-banner"><div><strong>{saved ? "Saved analysis" : "Current unsaved analysis"}</strong><span>{analysis.configuration.schoolYearLabel} · {analysis.configuration.capHours}-hour cap</span></div><button className="primary-button" onClick={onNewAnalysis}>＋ New analysis</button></div>
    <div className="stat-grid analysis-stats"><div className="stat-card accent-coral"><div className="stat-label">Needs review</div><div className="stat-value">{analysis.summary.flaggedOptionalEvents}</div><div className="stat-foot">optional events flagged</div></div><div className="stat-card"><div className="stat-label">Volunteers</div><div className="stat-value">{analysis.summary.volunteers}</div><div className="stat-foot">in this analysis</div></div><div className="stat-card"><div className="stat-label">Mandatory retained</div><div className="stat-value">{analysis.summary.mandatoryExemptEvents}</div><div className="stat-foot">exempt registrations</div></div><div className="stat-card warm-card"><div className="stat-label">Data warnings</div><div className="stat-value">{analysis.summary.warnings}</div><div className="stat-foot">review before acting</div></div></div>
    <div className="section-heading"><div><h2>Upcoming opportunity check</h2><p>Projected totals after each active registration</p></div><select className="filter-button" aria-label="Filter statuses" value={filter} onChange={(event) => setFilter(event.target.value)}><option value="all">All statuses</option><option value="flagged">Review / remove</option><option value="allowed">Allowed</option><option value="mandatory_exempt">Mandatory · exempt</option></select></div>
    <div className="table-card"><div className="table-meta"><span>{rows.length} event registrations</span><span className="meta-divider" /><span>{saved ? "Saved to History" : "Not saved to History"}</span></div>{visible.length === 0 ? <div className="empty-results">No registrations match this view.</div> : <div className="table-scroll"><table><thead><tr><th>VOLUNTEER</th><th>CURRENT HOURS</th><th>UPCOMING EVENT</th><th>DATE</th><th>PROJECTED</th><th>STATUS</th><th /></tr></thead><tbody>{visible.map((row) => { const key = `${row.volunteer.volunteerKey}-${row.event.eventName}`; return <tr key={`${key}-${row.event.eventDate}`}><td><div className="person-cell"><div className={`person-avatar ${row.event.classification === "mandatory_exempt" ? "teal" : ""}`}>{initials(row.volunteer.name)}</div><div><strong>{row.volunteer.name}</strong><span>{row.volunteer.email ?? "Email missing"}</span></div></div></td><td><strong className="hours-current">{formatHours(row.volunteer.currentValidatedHours)}</strong><span className="hours-unit"> hrs</span></td><td><span className={`event-name ${row.event.classification === "mandatory_exempt" ? "mandatory-name" : ""}`}>{row.event.eventName}</span><span className="duration">{formatHours(row.event.durationHours)} hours{row.event.warning ? ` · ⚠ ${row.event.warning}` : ""}</span></td><td className="date-cell">{new Date(row.event.eventDate).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" })}</td><td><strong className={row.event.classification === "flagged" ? "projected-hot" : "projected-ok"}>{formatHours(row.event.projectedHours)}</strong><span className="hours-unit"> hrs</span></td><td><span className={`status-pill ${row.event.classification === "flagged" ? "review" : row.event.classification === "allowed" ? "allowed" : "exempt"}`}><i />{label[row.event.classification]}</span></td><td>{row.event.draft && <button className="copy-button" onClick={() => copy(row)}>{copied === key ? "Copied" : "Copy email"}</button>}</td></tr>; })}</tbody></table></div>}<div className="table-bottom"><span><b>{analysis.summary.flaggedOptionalEvents}</b> optional events need review</span><span><b>{analysis.summary.mandatoryExemptEvents}</b> mandatory events retained</span></div></div>
    {analysis.performance && <PerformanceModule performance={analysis.performance} />}
    {analysis.teamMetrics && <TeamMetricsModule teamMetrics={analysis.teamMetrics} />}
  </>;
}
