import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("STUCO Hours Desk product surface is present", async () => {
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const modal = await readFile(new URL("../app/components/AnalysisUploadModal.tsx", import.meta.url), "utf8");
  const dashboard = await readFile(new URL("../app/components/AnalysisDashboard.tsx", import.meta.url), "utf8");
  const history = await readFile(new URL("../app/components/HistoryView.tsx", import.meta.url), "utf8");
  const detail = await readFile(new URL("../app/components/AnalysisDetailView.tsx", import.meta.url), "utf8");
  const performance = await readFile(new URL("../app/components/PerformanceModule.tsx", import.meta.url), "utf8");
  const teamMetrics = await readFile(new URL("../app/components/TeamMetricsModule.tsx", import.meta.url), "utf8");
  const officers = await readFile(new URL("../app/components/OfficersView.tsx", import.meta.url), "utf8");
  const invitePage = await readFile(new URL("../app/invite/page.tsx", import.meta.url), "utf8");
  const surface = `${page}\n${modal}\n${dashboard}\n${history}\n${detail}\n${performance}\n${teamMetrics}\n${officers}`;
  assert.match(surface, /Keep opportunities/);
  assert.match(surface, /School-year start/);
  assert.match(surface, /School-year end/);
  assert.match(surface, /Hour cap/);
  assert.match(surface, /Analyzing reports/);
  assert.match(surface, /Current unsaved analysis/);
  assert.match(surface, /Save this analysis to History/);
  assert.match(surface, /No saved analyses yet/);
  assert.match(surface, /IMMUTABLE ANALYSIS/);
  assert.match(surface, /Copy email/);
  assert.match(surface, /Full Roster/);
  assert.match(surface, /Top performers/);
  assert.match(surface, /Steady performers/);
  assert.match(surface, /Developing performers/);
  assert.match(surface, /Validated hours/);
  assert.match(surface, /Completed opportunities/);
  assert.match(surface, /Combined score/);
  assert.match(teamMetrics, /Team metrics/);
  assert.match(teamMetrics, /Total hours/);
  assert.match(teamMetrics, /Participation/);
  assert.match(teamMetrics, /Average hours/);
  assert.match(teamMetrics, /Median hours/);
  assert.match(teamMetrics, /Active volunteers/);
  assert.match(teamMetrics, /Zero-hour volunteers/);
  assert.match(teamMetrics, /Completed opportunities/);
  assert.match(teamMetrics, /Hours spread/);
  assert.match(teamMetrics, /Period Hours/);
  assert.match(teamMetrics, /Cumulative Hours/);
  assert.match(teamMetrics, /maximumFractionDigits:\s*2/);
  assert.match(page, /const navigate = \(tab/);
  assert.match(page, /setDetailId\(null\)/);
  assert.match(page, /onClick=\{\(\) => navigate\("Overview"\)\}/);
  assert.match(page, /onClick=\{\(\) => navigate\("History"\)\}/);
  assert.match(page, /onClick=\{\(\) => navigate\("Officers"\)\}/);
  assert.match(page, /<OfficersView/);
  assert.doesNotMatch(page, /COMING NEXT/);
  assert.match(officers, /Officer access/);
  assert.match(officers, /Invite officer/);
  assert.match(officers, /Copy link/);
  assert.match(officers, /Generate new link/);
  assert.match(officers, /Deactivate/);
  assert.match(officers, /Active officers/);
  assert.match(officers, /Inactive officers/);
  assert.match(officers, /Pending invitations/);
  assert.match(officers, /Retry/);
  assert.match(officers, /Send this private link only to/);
  assert.match(officers, /Accept invitation/);
  assert.match(invitePage, /<OfficersView invitationMode/);
  assert.doesNotMatch(surface, /Send email/);
  assert.doesNotMatch(page, /Om Chandge|Keerthi Thota/);
  assert.doesNotMatch(page, /codex-preview/);
});

test("Cloudflare compatibility flags are declared only once", async () => {
  const vite = await readFile(new URL("../vite.config.ts", import.meta.url), "utf8");
  const wrangler = await readFile(new URL("../wrangler.jsonc", import.meta.url), "utf8");
  const declarations = `${vite}\n${wrangler}`.match(/nodejs_compat/g) ?? [];
  assert.equal(declarations.length, 1);
});
