"use client";

import { useMemo, useState } from "react";

type Status = "Review / remove" | "Mandatory · exempt" | "Allowed";
type EventRow = { volunteer: string; initials: string; email: string; current: number; event: string; date: string; duration: number; projected: number; status: Status; mandatory?: boolean };

const eventRows: EventRow[] = [
  { volunteer: "Om Chandge", initials: "OC", email: "ochandge033@rsdmo.org", current: 24.5, event: "Fall Food Drive", date: "Sep 12, 2026", duration: 3.5, projected: 28, status: "Review / remove" },
  { volunteer: "Rishi Gudimalla", initials: "RG", email: "sgudimalla009@rsdmo.org", current: 24, event: "MANDATORY STUCO Meeting: Welcome!", date: "Sep 9, 2026", duration: 1, projected: 25, status: "Mandatory · exempt", mandatory: true },
  { volunteer: "Vihaan Madhavan", initials: "VM", email: "vmadhavan074@rsdmo.org", current: 18.5, event: "Fall Food Drive", date: "Sep 12, 2026", duration: 3.5, projected: 22, status: "Allowed" },
  { volunteer: "Keerthi Thota", initials: "KT", email: "kthota030@rsdmo.org", current: 25, event: "Student Council Welcome Lunch", date: "Sep 10, 2026", duration: 1.5, projected: 26.5, status: "Review / remove" },
];

const drafts: Record<string, string> = {
  "Om Chandge": "Hi Om,\n\nYou currently have 24.5 validated volunteer hours for the 2026–2027 school year. The Fall Food Drive on September 12 would bring your projected total to 28 hours. Because this is above our 25-hour limit, we need to remove you from this optional opportunity so more students have a chance to participate.\n\nThank you for understanding!",
  "Keerthi Thota": "Hi Keerthi,\n\nYou currently have 25 validated volunteer hours for the 2026–2027 school year. The Student Council Welcome Lunch on September 10 would bring your projected total to 26.5 hours. Because this is above our 25-hour limit, we need to remove you from this optional opportunity so more students have a chance to participate.\n\nThank you for understanding!",
};

export default function Home() {
  const [activeTab, setActiveTab] = useState("Overview");
  const [copied, setCopied] = useState<string | null>(null);
  const [showUpload, setShowUpload] = useState(false);
  const flagged = useMemo(() => eventRows.filter((row) => row.status === "Review / remove"), []);
  function copyDraft(volunteer: string) { const text = drafts[volunteer]; if (!text) return; navigator.clipboard?.writeText(text); setCopied(volunteer); window.setTimeout(() => setCopied(null), 1800); }

  return <main className="app-shell">
    <aside className="sidebar">
      <div className="brand-lockup"><div className="brand-mark">S</div><div><div className="brand-name">STUCO</div><div className="brand-subtitle">Hours desk</div></div></div>
      <div className="team-switcher"><span className="switcher-label">TEAM</span><div className="team-name">Marquette HS <span>⌄</span></div></div>
      <nav className="side-nav" aria-label="Primary navigation">{["Overview", "New analysis", "History", "Officers"].map((item, index) => <button key={item} className={`nav-item ${activeTab === item ? "active" : ""}`} onClick={() => item === "New analysis" ? setShowUpload(true) : setActiveTab(item)}><span className="nav-icon">{["◒", "+", "↺", "◎"][index]}</span><span>{item}</span>{item === "History" && <span className="nav-count">6</span>}</button>)}</nav>
      <div className="sidebar-footer"><div className="rule-card"><div className="rule-card-title">Current rule</div><div className="rule-card-value">25 <span>hours</span></div><div className="rule-card-note">2026–2027 school year</div></div><div className="profile-row"><div className="profile-avatar">RG</div><div className="profile-copy"><strong>Rishi Gudimalla</strong><span>Officer</span></div><button className="more-button" aria-label="Account menu">•••</button></div></div>
    </aside>
    <section className="main-panel">
      <header className="topbar"><div className="breadcrumb"><span>STUCO</span><b>/</b><strong>{activeTab}</strong></div><div className="topbar-actions"><span className="synced"><i /> Last synced today at 5:42 PM</span><button className="help-button" aria-label="Help">?</button></div></header>
      <div className="content-wrap"><div className="page-heading"><div><p className="eyebrow">TUESDAY, AUGUST 25, 2026</p><h1>Keep opportunities <em>fair.</em></h1><p className="heading-note">A quick view of who is approaching the 25-hour limit.</p></div><button className="primary-button" onClick={() => setShowUpload(true)}><span>＋</span> New analysis</button></div>
        <div className="stat-grid"><div className="stat-card accent-coral"><div className="stat-label">Needs review</div><div className="stat-value">{flagged.length}</div><div className="stat-foot">optional events flagged</div><div className="stat-spark coral-spark"><i /><i /><i /><i /><i /><i /><i /></div></div><div className="stat-card"><div className="stat-label">At the limit</div><div className="stat-value">3</div><div className="stat-foot">volunteers at 25 hours</div><div className="stat-ring"><span>25</span></div></div><div className="stat-card"><div className="stat-label">School-year hours</div><div className="stat-value">384.5</div><div className="stat-foot">validated across 21 volunteers</div><div className="stat-spark blue-spark"><i /><i /><i /><i /><i /><i /><i /></div></div><div className="stat-card warm-card"><div className="stat-label">Next opportunity</div><div className="stat-event">MANDATORY STUCO<br />Meeting: Welcome!</div><div className="stat-foot">Sep 9 · 1 hour · 2 registered</div><span className="exempt-pill">Exempt from removal</span></div></div>
        <div className="section-heading"><div><h2>Upcoming opportunity check</h2><p>Projected totals after each registered event</p></div><button className="filter-button">All statuses <span>⌄</span></button></div>
        <div className="table-card"><div className="table-meta"><span>4 event registrations</span><span className="meta-divider" /><span>Analysis #06 · created today</span><button className="download-button">Download list <span>↓</span></button></div><div className="table-scroll"><table><thead><tr><th>VOLUNTEER</th><th>CURRENT HOURS</th><th>UPCOMING EVENT</th><th>DATE</th><th>PROJECTED</th><th>STATUS</th><th /></tr></thead><tbody>{eventRows.map((row) => <tr key={`${row.volunteer}-${row.event}`}><td><div className="person-cell"><div className={`person-avatar ${row.mandatory ? "teal" : ""}`}>{row.initials}</div><div><strong>{row.volunteer}</strong><span>{row.email}</span></div></div></td><td><strong className="hours-current">{row.current}</strong><span className="hours-unit"> hrs</span></td><td><span className={`event-name ${row.mandatory ? "mandatory-name" : ""}`}>{row.event}</span><span className="duration">{row.duration} hours</span></td><td className="date-cell">{row.date}</td><td><strong className={row.status === "Review / remove" ? "projected-hot" : "projected-ok"}>{row.projected}</strong><span className="hours-unit"> hrs</span></td><td><span className={`status-pill ${row.status === "Review / remove" ? "review" : row.status === "Allowed" ? "allowed" : "exempt"}`}><i />{row.status}</span></td><td>{row.status === "Review / remove" && <button className="copy-button" onClick={() => copyDraft(row.volunteer)}>{copied === row.volunteer ? "Copied" : "Copy email"}</button>}</td></tr>)}</tbody></table></div><div className="table-bottom"><span><b>2</b> optional events need review</span><span><b>1</b> mandatory event retained automatically</span><a href="#rules">View calculation rules →</a></div></div>
        <div className="bottom-grid"><div className="info-card" id="rules"><div className="info-icon">✓</div><div><h3>How the rule works</h3><p>Validated hours count only inside the school-year dates. Events are checked in chronological order. The first optional event that takes someone above 25 hours is flagged. Anything marked <code>MANDATORY</code> is always retained.</p></div></div><div className="info-card peach"><div className="info-icon">↗</div><div><h3>Ready for the next handoff?</h3><p>Invite next year’s officers now. Everyone gets their own sign-in and the same permissions.</p><button onClick={() => setActiveTab("Officers")}>Manage officers →</button></div></div></div>
      </div>
    </section>
    {showUpload && <div className="modal-backdrop" onClick={() => setShowUpload(false)}><div className="upload-modal" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setShowUpload(false)} aria-label="Close">×</button><div className="modal-kicker">NEW ANALYSIS</div><h2>Bring in the latest reports.</h2><p>Upload both Helper Helper exports to calculate the next review list.</p><label className="upload-field"><span>01</span><div><strong>Team Report</strong><small>Completed and validated hours · .xlsx</small></div><input type="file" accept=".xlsx,.xls,.csv" /></label><label className="upload-field"><span>02</span><div><strong>Upcoming Opportunities</strong><small>Future registrations and event durations · .xlsx</small></div><input type="file" accept=".xlsx,.xls,.csv" /></label><div className="modal-rule"><span>Rule for this analysis</span><strong>25 hours <i>·</i> 2026–2027</strong></div><button className="primary-button full-width" onClick={() => setShowUpload(false)}>Analyze reports <span>→</span></button><p className="modal-note">Reports stay private to your STUCO team. No emails are sent automatically.</p></div></div>}
  </main>;
}
