"use client";
import { useState } from "react";
import type { AnalysisViewModel } from "./analysis-types";
import { AnalysisDashboard } from "./components/AnalysisDashboard";
import { AnalysisUploadModal } from "./components/AnalysisUploadModal";
export default function Home() {
  const [activeTab, setActiveTab] = useState("Overview"), [showUpload, setShowUpload] = useState(false), [analysis, setAnalysis] = useState<AnalysisViewModel | null>(null);
  const openAnalysis = () => { setActiveTab("New analysis"); setShowUpload(true); };
  return <main className="app-shell"><aside className="sidebar"><div className="brand-lockup"><div className="brand-mark">S</div><div><div className="brand-name">STUCO</div><div className="brand-subtitle">Hours desk</div></div></div><div className="team-switcher"><span className="switcher-label">TEAM</span><div className="team-name">Marquette HS</div></div><nav className="side-nav" aria-label="Primary navigation"><button className={`nav-item ${activeTab === "Overview" ? "active" : ""}`} onClick={() => setActiveTab("Overview")}><span className="nav-icon">◒</span><span>Overview</span></button><button className={`nav-item ${activeTab === "New analysis" ? "active" : ""}`} onClick={openAnalysis}><span className="nav-icon">＋</span><span>New analysis</span></button><button className={`nav-item ${activeTab === "History" ? "active" : ""}`} onClick={() => setActiveTab("History")}><span className="nav-icon">↺</span><span>History</span></button><button className={`nav-item ${activeTab === "Officers" ? "active" : ""}`} onClick={() => setActiveTab("Officers")}><span className="nav-icon">◎</span><span>Officers</span></button></nav><div className="sidebar-footer"><div className="rule-card"><div className="rule-card-title">Current analysis</div><div className="rule-card-value">{analysis?.configuration.capHours ?? 25} <span>hours</span></div><div className="rule-card-note">{analysis?.configuration.schoolYearLabel ?? "Choose dates when uploading"}</div></div></div></aside>
    <section className="main-panel"><header className="topbar"><div className="breadcrumb"><span>STUCO</span><b>/</b><strong>{activeTab}</strong></div><div className="topbar-actions"><span className="synced"><i /> Session-only results</span></div></header><div className="content-wrap">{activeTab === "History" || activeTab === "Officers" ? <div className="welcome-state"><p className="eyebrow">COMING NEXT</p><h1>{activeTab}</h1><p>This page will be connected after the New Analysis workflow and persistent storage are complete.</p><button className="primary-button" onClick={openAnalysis}>Start a new analysis</button></div> : <AnalysisDashboard analysis={analysis} onNewAnalysis={openAnalysis} />}</div></section>
    <AnalysisUploadModal open={showUpload} onClose={() => setShowUpload(false)} onSuccess={(result) => { setAnalysis(result); setActiveTab("Overview"); }} />
  </main>;
}
